/*
Copyright 2019-2020 vChain, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package schema

import (
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
)

// PatternImmuServiceGetBatch0 exposes the runtime Pattern need to overwrite getbatch autogenerated request
func PatternImmuServiceGetBatch0() runtime.Pattern {
	return pattern_ImmuService_GetBatch_0
}

// PatternImmuServiceSetBatch0 exposes the runtime Pattern need to overwrite setbatch autogenerated request
func PatternImmuServiceSetBatch0() runtime.Pattern {
	return pattern_ImmuService_SetBatch_0
}

// PatternImmuServiceIScan0 exposes the runtime Pattern need to overwrite iscan autogenerated request
func PatternImmuServiceIScan0() runtime.Pattern {
	return pattern_ImmuService_IScan_0
}

// PatternImmuServiceCount0 exposes the runtime Pattern need to overwrite count autogenerated request
func PatternImmuServiceCount0() runtime.Pattern {
	return pattern_ImmuService_Count_0
}

// PatternImmuServiceByIndex0 exposes the runtime Pattern need to overwrite byindex autogenerated request
func PatternImmuServiceByIndex0() runtime.Pattern {
	return pattern_ImmuService_ByIndex_0
}

// PatternImmuServiceGet0 exposes the runtime Pattern need to overwrite get autogenerated request
func PatternImmuServiceGet0() runtime.Pattern {
	return pattern_ImmuService_Get_0
}

// PatternImmuServiceSafeGet0 exposes the runtime Pattern need to overwrite safeget autogenerated request
func PatternImmuServiceSafeGet0() runtime.Pattern {
	return pattern_ImmuService_SafeGet_0
}

// PatternImmuServiceSafeSet0 exposes the runtime Pattern need to overwrite safeset autogenerated request
func PatternImmuServiceSafeSet0() runtime.Pattern {
	return pattern_ImmuService_SafeSet_0
}

// PatternImmuServiceSet0 exposes the runtime Pattern need to overwrite set autogenerated request
func PatternImmuServiceSet0() runtime.Pattern {
	return pattern_ImmuService_Set_0
}

// PatternImmuServiceHistory0 exposes the runtime Pattern need to overwrite history autogenerated request
func PatternImmuServiceHistory0() runtime.Pattern {
	return pattern_ImmuService_History_0
}

// PatternImmuServiceSafeReference0 exposes the runtime Pattern need to overwrite safeReference autogenerated request
func PatternImmuServiceSafeReference0() runtime.Pattern {
	return pattern_ImmuService_SafeReference_0
}

// PatternImmuServiceSafeZAdd0 exposes the runtime Pattern need to overwrite SafeZAdd autogenerated request
func PatternImmuServiceSafeZAdd0() runtime.Pattern {
	return pattern_ImmuService_SafeZAdd_0
}
